import {
  LOADING,
  DISMISS_LOADING,
  NO_INTERNET_CONNECTION,
  INTERNAL_SERVER_ERROR,
  NOT_AUTHORIZED,
  CLEAR_STATE,
  SUCCESS,
  SEPARATOR,
  CLEAR_STATE_ALL,
} from "./BaseTypes";

export const SEARCH_TREND_PREFIX = "SEARCH_TREND";

export const SEARCH_TREND_LOADING = SEARCH_TREND_PREFIX + SEPARATOR + LOADING;

export const SEARCH_TREND_DISMISS_LOADING =
  SEARCH_TREND_PREFIX + SEPARATOR + DISMISS_LOADING;

export const SEARCH_TREND_NO_INTERNET_CONNECTION =
  SEARCH_TREND_PREFIX + SEPARATOR + NO_INTERNET_CONNECTION;

export const SEARCH_TREND_INTERNAL_SERVER_ERROR =
  SEARCH_TREND_PREFIX + SEPARATOR + INTERNAL_SERVER_ERROR;

export const SEARCH_TREND_NOT_AUTHORIZED =
  SEARCH_TREND_PREFIX + SEPARATOR + NOT_AUTHORIZED;

export const SEARCH_TREND_NO_DATA_FOUND =
  SEARCH_TREND_PREFIX + SEPARATOR + SUCCESS;

export const SEARCH_TREND_SUCCESS = SEARCH_TREND_PREFIX + SEPARATOR + SUCCESS;

export const SEARCH_TREND_CLEAR_STATE =
  SEARCH_TREND_PREFIX + SEPARATOR + CLEAR_STATE;

export const SEARCH_TREND_CLEAR_STATE_ALL =
  SEARCH_TREND_PREFIX + SEPARATOR + CLEAR_STATE_ALL;
