import {
  LOADING,
  DISMISS_LOADING,
  NO_INTERNET_CONNECTION,
  INTERNAL_SERVER_ERROR,
  NOT_AUTHORIZED,
  CLEAR_STATE,
  SUCCESS,
  SEPARATOR,
  CLEAR_STATE_ALL,
} from "./BaseTypes";

export const STATUS_UPDATES_PREFIX = "STATUS_UPDATES";

export const STATUS_UPDATES_LOADING =
  STATUS_UPDATES_PREFIX + SEPARATOR + LOADING;

export const STATUS_UPDATES_DISMISS_LOADING =
  STATUS_UPDATES_PREFIX + SEPARATOR + DISMISS_LOADING;

export const STATUS_UPDATES_NO_INTERNET_CONNECTION =
  STATUS_UPDATES_PREFIX + SEPARATOR + NO_INTERNET_CONNECTION;

export const STATUS_UPDATES_INTERNAL_SERVER_ERROR =
  STATUS_UPDATES_PREFIX + SEPARATOR + INTERNAL_SERVER_ERROR;

export const STATUS_UPDATES_NOT_AUTHORIZED =
  STATUS_UPDATES_PREFIX + SEPARATOR + NOT_AUTHORIZED;

export const STATUS_UPDATES_NO_DATA_FOUND =
  STATUS_UPDATES_PREFIX + SEPARATOR + SUCCESS;

export const STATUS_UPDATES_SUCCESS =
  STATUS_UPDATES_PREFIX + SEPARATOR + SUCCESS;

export const STATUS_UPDATES_CLEAR_STATE =
  STATUS_UPDATES_PREFIX + SEPARATOR + CLEAR_STATE;

export const STATUS_UPDATES_CLEAR_STATE_ALL =
  STATUS_UPDATES_PREFIX + SEPARATOR + CLEAR_STATE_ALL;
